 

GET http://localhost:5000/places

###

GET http://localhost:5000/places/id/5f3eb98b372984107d16d704
###
POST http://localhost:5000/places
Content-Type: application/json

{
    "name" : "Hiho",
    "wifi" : true,
    "price_night" : 150
}
###

GET http://fathomless-crag-75187.herokuapp.com/


###
POST http://fathomless-crag-75187.herokuapp.com/
Content-Type: application/json

{
    "name" : "Hi there",
    "wifi" : false,
    "price_night" : 100
}


###
PATCH http://localhost:5000/places/5f3bf251af5c4518951b945a
Content-Type: application/json

{
    "name" : "LOLLOL"
}

###

DELETE http://localhost:5000/places/5f3bf251af5c4518951b9459

###
POST http://localhost:5000/places/special/
Content-Type: application/json

{
    "area" : "negev",
    "animal" : true,
    "handicap" : true,
    "shaabaat_keep" : false
}

###
GET  http://localhost:5000/places/locations2/   
###


###
GET  http://localhost:5000/places/locations/
###

###
GET  http://localhost:5000/

###
GET  http://localhost:5000/locations/israel/

###